-- ============================================================================
-- V1__schema.sql  (CONSOLIDADO - reemplaza a los antiguos V1..V8)
-- Esquema completo de la aplicación Library Ultimate.
--
-- Incluye en un SOLO script:
--   * Tablas base (modules, permissions, roles, role_permissions, users)
--   * Columnas de auditoría + borrado lógico (created_at, updated_at,
--     created_by, updated_by, deleted_at, deleted_by) en TODAS las entidades
--   * Columna `enabled` en modules, roles y permissions
--   * Tablas de auditoría Envers (REVINFO + *_AUD + role_permissions_AUD)
--
-- Gestionado por Flyway. Hibernate usa hbm2ddl.auto=validate y NO modifica el
-- esquema; estas columnas deben coincidir exactamente con las entidades JPA.
-- ============================================================================

-- Módulos ----------------------------------------------------------------
CREATE TABLE modules (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    menu_label   VARCHAR(150),
    icon         VARCHAR(100),
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);

-- Permisos ---------------------------------------------------------------
CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL UNIQUE,
    name        VARCHAR(150) NOT NULL,
    menu_label  VARCHAR(255),
    icon        VARCHAR(100),
    url         VARCHAR(255),
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    module_id   BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    CONSTRAINT fk_permissions_module FOREIGN KEY (module_id) REFERENCES modules (id)
);

-- Roles ------------------------------------------------------------------
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(255),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50)
);

-- Join table roles <-> permissions (many-to-many) ------------------------
CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES roles (id),
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

-- Usuarios ---------------------------------------------------------------
CREATE TABLE users (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  VARCHAR(50)  NOT NULL UNIQUE,
    password  VARCHAR(255) NOT NULL, -- nunca en texto plano; guarda el hash Argon2id
    full_name VARCHAR(150),
    email     VARCHAR(120) UNIQUE,
    enabled   BOOLEAN      NOT NULL DEFAULT TRUE,
    role_id   BIGINT       NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

-- ============================================================================
-- Tablas de auditoría Envers
-- ============================================================================

-- Revisión central (naming por defecto de Envers).
CREATE TABLE REVINFO (
    REV BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REVTSTMP BIGINT, -- commit timestamp en milisegundos
    username VARCHAR(50)
);

-- Auditoría de usuarios ------------------------------------------------------
CREATE TABLE users_AUD (
    id         BIGINT NOT NULL,
    REV BIGINT NOT NULL,
    REVTYPE    SMALLINT,
    username   VARCHAR(50),
    password   VARCHAR(255),
    full_name  VARCHAR(150),
    email      VARCHAR(120),
    enabled    BOOLEAN,
    role_id    BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_users_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Auditoría de roles ---------------------------------------------------------
CREATE TABLE roles_AUD (
    id          BIGINT NOT NULL,
    REV BIGINT NOT NULL,
    REVTYPE     SMALLINT,
    name        VARCHAR(50),
    description VARCHAR(255),
    enabled     BOOLEAN,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_roles_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Auditoría de la join table roles <-> permissions ---------------------------
CREATE TABLE role_permissions_AUD (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    REV BIGINT NOT NULL,
    REVTYPE       SMALLINT,
    PRIMARY KEY (role_id, permission_id, REV),
    CONSTRAINT fk_rp_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Auditoría de permisos ------------------------------------------------------
CREATE TABLE permissions_AUD (
    id          BIGINT NOT NULL,
    REV BIGINT NOT NULL,
    REVTYPE     SMALLINT,
    code        VARCHAR(100),
    name        VARCHAR(150),
    menu_label  VARCHAR(255),
    icon        VARCHAR(100),
    url         VARCHAR(255),
    sort_order  INTEGER,
    enabled     BOOLEAN,
    module_id   BIGINT,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_permissions_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Auditoría de módulos -------------------------------------------------------
CREATE TABLE modules_AUD (
    id          BIGINT NOT NULL,
    REV BIGINT NOT NULL,
    REVTYPE     SMALLINT,
    code        VARCHAR(50),
    name        VARCHAR(100),
    menu_label  VARCHAR(150),
    icon        VARCHAR(100),
    sort_order  INTEGER,
    enabled     BOOLEAN,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_modules_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
