-- ============================================================================
-- V12__author_roles.sql
-- Tabla de roles de autor y modificación de tablas de relación.
-- ============================================================================

-- Author Roles ---------------------------------------------------------------
CREATE TABLE author_roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(255),
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);

-- Seed author_roles ----------------------------------------------------------
INSERT INTO author_roles (code, name, description, created_at, updated_at) VALUES ('LEAD_AUTHOR', 'Lead Author', 'Primary author of the work', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO author_roles (code, name, description, created_at, updated_at) VALUES ('CO_AUTHOR', 'Co-Author', 'Contributing author', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO author_roles (code, name, description, created_at, updated_at) VALUES ('EDITOR', 'Editor', 'Editor of the work', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO author_roles (code, name, description, created_at, updated_at) VALUES ('TRANSLATOR', 'Translator', 'Translator of the work', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO author_roles (code, name, description, created_at, updated_at) VALUES ('CONTRIBUTOR', 'Contributor', 'Contributor to the work', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Modify work_authors --------------------------------------------------------
ALTER TABLE work_authors ADD COLUMN IF NOT EXISTS author_role_id BIGINT;
ALTER TABLE work_authors ALTER COLUMN role DROP NOT NULL;
UPDATE work_authors SET author_role_id = (SELECT id FROM author_roles WHERE code = 'LEAD_AUTHOR') WHERE author_role_id IS NULL;
ALTER TABLE work_authors ALTER COLUMN author_role_id SET NOT NULL;
ALTER TABLE work_authors ADD CONSTRAINT fk_work_authors_role FOREIGN KEY (author_role_id) REFERENCES author_roles (id);

-- Modify edition_authors -----------------------------------------------------
ALTER TABLE edition_authors ADD COLUMN IF NOT EXISTS author_role_id BIGINT;
ALTER TABLE edition_authors ALTER COLUMN role DROP NOT NULL;
UPDATE edition_authors SET author_role_id = (SELECT id FROM author_roles WHERE code = 'LEAD_AUTHOR') WHERE author_role_id IS NULL;
ALTER TABLE edition_authors ALTER COLUMN author_role_id SET NOT NULL;
ALTER TABLE edition_authors ADD CONSTRAINT fk_edition_authors_role FOREIGN KEY (author_role_id) REFERENCES author_roles (id);

-- ============================================================================
-- Tablas de auditoría Envers
-- ============================================================================

CREATE TABLE author_roles_AUD (
    id           BIGINT NOT NULL,
    REV BIGINT NOT NULL,
    REVTYPE      SMALLINT,
    code         VARCHAR(50),
    name         VARCHAR(100),
    description  VARCHAR(255),
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_author_roles_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

ALTER TABLE work_authors_AUD ADD COLUMN IF NOT EXISTS author_role_id BIGINT;
ALTER TABLE edition_authors_AUD ADD COLUMN IF NOT EXISTS author_role_id BIGINT;
