-- ============================================================================
-- V5__books_schema.sql
-- Tablas del módulo Books (Works, Editions, Authors, Publishers, Languages,
-- BookFormats, Categories) y sus tablas de auditoría Envers.
-- ============================================================================

-- Works ----------------------------------------------------------------------
CREATE TABLE works (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(300)  NOT NULL,
    subtitle              VARCHAR(500),
    original_language_id  BIGINT,
    category_id           BIGINT,
    summary               VARCHAR(2000),
    enabled               BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP(6) WITH TIME ZONE,
    updated_at            TIMESTAMP(6) WITH TIME ZONE,
    created_by            VARCHAR(50),
    updated_by            VARCHAR(50),
    deleted_at            TIMESTAMP(6) WITH TIME ZONE,
    deleted_by            VARCHAR(50)
);

-- Authors --------------------------------------------------------------------
CREATE TABLE authors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    biography   VARCHAR(2000),
    birth_date  VARCHAR(20),
    death_date  VARCHAR(20),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50)
);

-- Publishers ----------------------------------------------------------------
CREATE TABLE publishers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL UNIQUE,
    country     VARCHAR(100),
    website     VARCHAR(300),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50)
);

-- Languages -----------------------------------------------------------------
CREATE TABLE languages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(10)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50)
);

-- Book Formats --------------------------------------------------------------
CREATE TABLE book_formats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50)
);

-- Categories ----------------------------------------------------------------
CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL UNIQUE,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    parent_id   BIGINT,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

-- Editions -------------------------------------------------------------------
CREATE TABLE editions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id           BIGINT       NOT NULL,
    publisher_id      BIGINT       NOT NULL,
    format_id         BIGINT       NOT NULL,
    language_id       BIGINT       NOT NULL,
    isbn              VARCHAR(20),
    pages             INTEGER,
    publication_year  INTEGER,
    edition_number    VARCHAR(50)  NOT NULL,
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    created_by        VARCHAR(50),
    updated_by        VARCHAR(50),
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    deleted_by        VARCHAR(50),
    CONSTRAINT fk_editions_work      FOREIGN KEY (work_id)      REFERENCES works (id),
    CONSTRAINT fk_editions_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id),
    CONSTRAINT fk_editions_format    FOREIGN KEY (format_id)    REFERENCES book_formats (id),
    CONSTRAINT fk_editions_language  FOREIGN KEY (language_id)  REFERENCES languages (id)
);

-- ============================================================================
-- Tablas de auditoría Envers
-- ============================================================================

CREATE TABLE works_AUD (
    id                   BIGINT NOT NULL,
    REV                  INTEGER NOT NULL,
    REVTYPE              SMALLINT,
    title                VARCHAR(300),
    subtitle             VARCHAR(500),
    original_language_id BIGINT,
    category_id          BIGINT,
    summary              VARCHAR(2000),
    enabled              BOOLEAN,
    created_at           TIMESTAMP(6) WITH TIME ZONE,
    updated_at           TIMESTAMP(6) WITH TIME ZONE,
    created_by           VARCHAR(50),
    updated_by           VARCHAR(50),
    deleted_at           TIMESTAMP(6) WITH TIME ZONE,
    deleted_by           VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_works_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE editions_AUD (
    id               BIGINT NOT NULL,
    REV              INTEGER NOT NULL,
    REVTYPE          SMALLINT,
    work_id          BIGINT,
    publisher_id     BIGINT,
    format_id        BIGINT,
    language_id      BIGINT,
    isbn             VARCHAR(20),
    pages            INTEGER,
    publication_year INTEGER,
    edition_number   VARCHAR(50),
    enabled          BOOLEAN,
    created_at       TIMESTAMP(6) WITH TIME ZONE,
    updated_at       TIMESTAMP(6) WITH TIME ZONE,
    created_by       VARCHAR(50),
    updated_by       VARCHAR(50),
    deleted_at       TIMESTAMP(6) WITH TIME ZONE,
    deleted_by       VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_editions_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE authors_AUD (
    id          BIGINT NOT NULL,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    first_name  VARCHAR(100),
    last_name   VARCHAR(100),
    biography   VARCHAR(2000),
    birth_date  VARCHAR(20),
    death_date  VARCHAR(20),
    enabled     BOOLEAN,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_authors_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE publishers_AUD (
    id          BIGINT NOT NULL,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    name        VARCHAR(200),
    country     VARCHAR(100),
    website     VARCHAR(300),
    enabled     BOOLEAN,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_publishers_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE languages_AUD (
    id          BIGINT NOT NULL,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    code        VARCHAR(10),
    name        VARCHAR(100),
    enabled     BOOLEAN,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_languages_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE book_formats_AUD (
    id          BIGINT NOT NULL,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    code        VARCHAR(50),
    name        VARCHAR(100),
    description VARCHAR(500),
    enabled     BOOLEAN,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_book_formats_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE categories_AUD (
    id          BIGINT NOT NULL,
    REV         INTEGER NOT NULL,
    REVTYPE     SMALLINT,
    code        VARCHAR(50),
    name        VARCHAR(150),
    description VARCHAR(1000),
    parent_id   BIGINT,
    enabled     BOOLEAN,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_categories_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
