-- ============================================================================
-- V8__books_work_authors_and_edition_authors.sql
-- Tablas de relación muchos-a-muchos entre Works-Authors y Editions-Authors,
-- y sus tablas de auditoría Envers.
-- ============================================================================

-- Work Authors ---------------------------------------------------------------
CREATE TABLE work_authors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id      BIGINT       NOT NULL,
    author_id    BIGINT       NOT NULL,
    role         VARCHAR(100),
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    CONSTRAINT fk_work_authors_work   FOREIGN KEY (work_id)   REFERENCES works (id),
    CONSTRAINT fk_work_authors_author FOREIGN KEY (author_id) REFERENCES authors (id)
);

-- Edition Authors ------------------------------------------------------------
CREATE TABLE edition_authors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id   BIGINT       NOT NULL,
    author_id    BIGINT       NOT NULL,
    role         VARCHAR(100),
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    CONSTRAINT fk_edition_authors_edition FOREIGN KEY (edition_id) REFERENCES editions (id),
    CONSTRAINT fk_edition_authors_author  FOREIGN KEY (author_id)  REFERENCES authors (id)
);

-- Seed work_authors ---------------------------------------------------------
INSERT INTO work_authors (work_id, author_id, role, enabled, created_at, updated_at) VALUES (1, 1, 'Author', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO work_authors (work_id, author_id, role, enabled, created_at, updated_at) VALUES (2, 2, 'Author', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO work_authors (work_id, author_id, role, enabled, created_at, updated_at) VALUES (3, 3, 'Author', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- ============================================================================
-- Tablas de auditoría Envers
-- ============================================================================

CREATE TABLE work_authors_AUD (
    id           BIGINT NOT NULL,
    REV          INTEGER NOT NULL,
    REVTYPE      SMALLINT,
    work_id      BIGINT,
    author_id    BIGINT,
    role         VARCHAR(100),
    enabled      BOOLEAN,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_work_authors_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE edition_authors_AUD (
    id           BIGINT NOT NULL,
    REV          INTEGER NOT NULL,
    REVTYPE      SMALLINT,
    edition_id   BIGINT,
    author_id    BIGINT,
    role         VARCHAR(100),
    enabled      BOOLEAN,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_edition_authors_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
