-- ============================================================================
-- V14__stock.sql
-- Stock module tables: stock_locations, stock_items, stock_movements.
-- Also adds module, permissions, and seeds for ADMIN and EMPLOYEE roles.
-- ============================================================================

-- Stock Locations -----------------------------------------------------------
CREATE TABLE stock_locations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    capacity        INTEGER,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    CONSTRAINT uk_stock_locations_code UNIQUE (code)
);

-- Stock Items ----------------------------------------------------------------
CREATE TABLE stock_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    edition_id      BIGINT       NOT NULL,
    location_id     BIGINT       NOT NULL,
    state           VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',
    condition       VARCHAR(20)  NOT NULL DEFAULT 'GOOD',
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    CONSTRAINT uk_stock_items_code UNIQUE (code),
    CONSTRAINT fk_stock_items_edition  FOREIGN KEY (edition_id)   REFERENCES editions (id),
    CONSTRAINT fk_stock_items_location FOREIGN KEY (location_id)  REFERENCES stock_locations (id)
);

-- Stock Movements -----------------------------------------------------------
CREATE TABLE stock_movements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(20)  NOT NULL,
    stock_item_id       BIGINT       NOT NULL,
    source_location_id  BIGINT,
    target_location_id  BIGINT,
    reason              VARCHAR(500),
    created_at          TIMESTAMP(6) WITH TIME ZONE,
    created_by          VARCHAR(50),
    CONSTRAINT fk_stock_movements_item      FOREIGN KEY (stock_item_id)        REFERENCES stock_items (id),
    CONSTRAINT fk_stock_movements_source    FOREIGN KEY (source_location_id)   REFERENCES stock_locations (id),
    CONSTRAINT fk_stock_movements_target    FOREIGN KEY (target_location_id)   REFERENCES stock_locations (id)
);

-- ============================================================================
-- Módulo Stock: permisos y grants
-- ============================================================================

INSERT INTO modules (code, name, menu_label, icon, sort_order, enabled) VALUES
    ('stock', 'Stock', 'Stock', 'bi-box-seam', 4, TRUE);

INSERT INTO permissions (code, name, menu_label, icon, url, sort_order, module_id) VALUES
    -- Stock Items
    ('stock.create',       'Create Stock Items',     NULL,            NULL, NULL, 10, 4),
    ('stock.read',         'View Stock Items',       'Stock Items',   'bi-box-seam', '/stock/items', 11, 4),
    ('stock.update',       'Edit Stock Items',       NULL,            NULL, NULL, 12, 4),
    ('stock.delete',       'Delete Stock Items',     NULL,            NULL, NULL, 13, 4),
    ('stock.reactivate',   'Reactivate Stock Items', NULL,            NULL, NULL, 14, 4),
    -- Stock Locations
    ('stocklocations.create',  'Create Locations',     NULL,           NULL, NULL, 20, 4),
    ('stocklocations.read',    'View Locations',       'Locations',    'bi-geo-alt', '/stock/locations', 21, 4),
    ('stocklocations.update',  'Edit Locations',       NULL,           NULL, NULL, 22, 4),
    ('stocklocations.delete',  'Delete Locations',     NULL,           NULL, NULL, 23, 4),
    ('stocklocations.reactivate', 'Reactivate Locations', NULL,       NULL, NULL, 24, 4);

-- Grant all stock permissions to ADMIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN'
  AND p.module_id = 4;

-- Seed initial stock locations
INSERT INTO stock_locations (code, name, description, capacity, enabled) VALUES
    ('SHLF-A1', 'Shelf A1', 'Fiction - Section A1', 100, TRUE),
    ('SHLF-A2', 'Shelf A2', 'Fiction - Section A2', 100, TRUE),
    ('SHLF-B1', 'Shelf B1', 'Non-Fiction - Section B1', 80, TRUE),
    ('RESERVE', 'Reserved Shelf', 'New arrivals and reserved items', 50, TRUE);

-- ============================================================================
-- Envers audit tables (_AUD) for @Audited stock entities.
-- REVINFO table already created in V1 (IAM schema migration).
-- ============================================================================

-- Auditoría de stock_locations
CREATE TABLE stock_locations_AUD (
    id           BIGINT NOT NULL,
    REV          BIGINT NOT NULL,
    REVTYPE      SMALLINT,
    code         VARCHAR(50),
    name         VARCHAR(100),
    description  VARCHAR(500),
    capacity     INTEGER,
    enabled      BOOLEAN,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_stock_locations_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Auditoría de stock_items
CREATE TABLE stock_items_AUD (
    id           BIGINT NOT NULL,
    REV          BIGINT NOT NULL,
    REVTYPE      SMALLINT,
    code         VARCHAR(50),
    edition_id   BIGINT,
    location_id  BIGINT,
    state        VARCHAR(20),
    condition    VARCHAR(20),
    enabled      BOOLEAN,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_stock_items_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Auditoría de stock_movements
CREATE TABLE stock_movements_AUD (
    id              BIGINT NOT NULL,
    REV             BIGINT NOT NULL,
    REVTYPE         SMALLINT,
    type            VARCHAR(20),
    stock_item_id   BIGINT,
    source_location_id BIGINT,
    target_location_id BIGINT,
    reason          VARCHAR(500),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_stock_movements_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
