-- ============================================================================
-- V16__client.sql
-- Client module table: clients.
-- Also adds module, permissions, and seeds for ADMIN and EMPLOYEE roles.
-- ============================================================================

-- Clients ------------------------------------------------------------------------
CREATE TABLE clients (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    dni             VARCHAR(20)  NOT NULL,
    full_name       VARCHAR(150) NOT NULL,
    email           VARCHAR(150),
    phone           VARCHAR(20),
    address         VARCHAR(300),
    type            VARCHAR(20)  NOT NULL DEFAULT 'CASUAL',
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    member_since    DATE,
    member_until    DATE,
    birth_date      DATE,
    notes           VARCHAR(500),
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    CONSTRAINT uk_clients_code UNIQUE (code),
    CONSTRAINT uk_clients_dni UNIQUE (dni)
);

-- ============================================================================
-- Módulo Client: permisos y grants
-- ============================================================================

INSERT INTO modules (code, name, menu_label, icon, sort_order, enabled) VALUES
    ('client', 'Clients', 'Clients', 'bi-people', 5, TRUE);

INSERT INTO permissions (code, name, menu_label, icon, url, sort_order, module_id) VALUES
    ('clients.create',       'Create Clients',     NULL,            NULL, NULL, 10, 5),
    ('clients.read',         'View Clients',       'Clients',       'bi-people', '/clients', 11, 5),
    ('clients.update',       'Edit Clients',       NULL,            NULL, NULL, 12, 5),
    ('clients.delete',       'Delete Clients',     NULL,            NULL, NULL, 13, 5),
    ('clients.reactivate',   'Reactivate Clients', NULL,            NULL, NULL, 14, 5);

-- Grant all client permissions to ADMIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN'
  AND p.module_id = 5;

-- Grant read permission to EMPLOYEE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE'
  AND p.code = 'clients.read';

-- Seed initial clients
INSERT INTO clients (code, dni, full_name, email, phone, address, type, status, member_since, enabled) VALUES
    ('CLI-A1B2C3', '12345678A', 'John Doe', 'john@example.com', '+1234567890', '123 Main St', 'CASUAL', 'ACTIVE', CURRENT_DATE, TRUE),
    ('CLI-D4E5F6', '87654321B', 'Jane Smith', 'jane@example.com', '+0987654321', '456 Oak Ave', 'MEMBER', 'ACTIVE', CURRENT_DATE, TRUE);

-- ============================================================================
-- Envers audit tables (_AUD) for @Audited client entities.
-- REVINFO table already created in V1 (IAM schema migration).
-- ============================================================================

-- Auditoría de clients
CREATE TABLE clients_AUD (
    id              BIGINT NOT NULL,
    REV             BIGINT NOT NULL,
    REVTYPE         SMALLINT,
    code            VARCHAR(50),
    dni             VARCHAR(20),
    full_name       VARCHAR(150),
    email           VARCHAR(150),
    phone           VARCHAR(20),
    address         VARCHAR(300),
    type            VARCHAR(20),
    status          VARCHAR(20),
    member_since    DATE,
    member_until    DATE,
    birth_date      DATE,
    notes           VARCHAR(500),
    enabled         BOOLEAN,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_clients_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
