-- ============================================================================
-- V1__schema.sql
-- Full database schema + audit tables.
-- ============================================================================

-- IAM
CREATE TABLE modules (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    menu_label   VARCHAR(150),
    icon         VARCHAR(100),
    sort_order   INTEGER      NOT NULL DEFAULT 0,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);

CREATE TABLE permissions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(100) NOT NULL UNIQUE,
    name        VARCHAR(150) NOT NULL,
    menu_label  VARCHAR(255),
    icon        VARCHAR(100),
    url         VARCHAR(255),
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    module_id   BIGINT       NOT NULL,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50),
    CONSTRAINT fk_permissions_module FOREIGN KEY (module_id) REFERENCES modules (id)
);

CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(255),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by  VARCHAR(50),
    updated_by  VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by  VARCHAR(50)
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_rp_role       FOREIGN KEY (role_id)       REFERENCES roles (id),
    CONSTRAINT fk_rp_permission FOREIGN KEY (permission_id) REFERENCES permissions (id)
);

CREATE TABLE users (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username              VARCHAR(50)  NOT NULL UNIQUE,
    password              VARCHAR(255) NOT NULL,
    full_name             VARCHAR(150),
    email                 VARCHAR(120) UNIQUE,
    enabled               BOOLEAN      NOT NULL DEFAULT TRUE,
    failed_login_attempts INTEGER      NOT NULL DEFAULT 0,
    locked_until          TIMESTAMP(6) WITH TIME ZONE,
    role_id               BIGINT       NOT NULL,
    created_at            TIMESTAMP(6) WITH TIME ZONE,
    updated_at            TIMESTAMP(6) WITH TIME ZONE,
    created_by            VARCHAR(50),
    updated_by            VARCHAR(50),
    deleted_at            TIMESTAMP(6) WITH TIME ZONE,
    deleted_by            VARCHAR(50),
    CONSTRAINT fk_users_role FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE security_audit_events (
    id          VARCHAR(100) PRIMARY KEY,
    event_type  VARCHAR(100) NOT NULL,
    user_id     VARCHAR(50),
    ip_address  VARCHAR(45),
    details     VARCHAR(500),
    timestamp   TIMESTAMP NOT NULL,
    severity    VARCHAR(20) NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- BOOKS
CREATE TABLE works (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                 VARCHAR(300)  NOT NULL,
    subtitle              VARCHAR(500),
    original_language_id  BIGINT,
    category_id           BIGINT,
    summary               VARCHAR(2000),
    enabled               BOOLEAN       NOT NULL DEFAULT TRUE,
    created_at            TIMESTAMP(6) WITH TIME ZONE,
    updated_at            TIMESTAMP(6) WITH TIME ZONE,
    created_by            VARCHAR(50),
    updated_by            VARCHAR(50),
    deleted_at            TIMESTAMP(6) WITH TIME ZONE,
    deleted_by            VARCHAR(50)
);

CREATE TABLE authors (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    biography   VARCHAR(2000),
    birth_date  VARCHAR(20),
    death_date  VARCHAR(20),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50)
);

CREATE TABLE publishers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    country     VARCHAR(100),
    website     VARCHAR(300),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50)
);

CREATE TABLE languages (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50)
);

CREATE TABLE book_formats (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50)
);

CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(50)  NOT NULL,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    parent_id   BIGINT,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP(6) WITH TIME ZONE,
    updated_at  TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50),
    updated_by VARCHAR(50),
    deleted_at  TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50),
    CONSTRAINT fk_categories_parent FOREIGN KEY (parent_id) REFERENCES categories (id)
);

CREATE TABLE editions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id           BIGINT       NOT NULL,
    publisher_id      BIGINT       NOT NULL,
    format_id         BIGINT       NOT NULL,
    language_id       BIGINT       NOT NULL,
    isbn              VARCHAR(20),
    pages             INTEGER,
    publication_year  INTEGER,
    edition_number    VARCHAR(50)  NOT NULL,
    daily_price       DECIMAL(10,2),
    enabled           BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at        TIMESTAMP(6) WITH TIME ZONE,
    updated_at        TIMESTAMP(6) WITH TIME ZONE,
    created_by        VARCHAR(50),
    updated_by        VARCHAR(50),
    deleted_at        TIMESTAMP(6) WITH TIME ZONE,
    deleted_by        VARCHAR(50),
    CONSTRAINT fk_editions_work      FOREIGN KEY (work_id)      REFERENCES works (id),
    CONSTRAINT fk_editions_publisher FOREIGN KEY (publisher_id) REFERENCES publishers (id),
    CONSTRAINT fk_editions_format    FOREIGN KEY (format_id)    REFERENCES book_formats (id),
    CONSTRAINT fk_editions_language  FOREIGN KEY (language_id)  REFERENCES languages (id)
);

CREATE TABLE author_roles (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL,
    name         VARCHAR(100) NOT NULL,
    description  VARCHAR(255),
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);

CREATE TABLE work_authors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_id      BIGINT       NOT NULL,
    author_id    BIGINT       NOT NULL,
    author_role_id BIGINT,
    role         VARCHAR(100),
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    CONSTRAINT fk_work_authors_work    FOREIGN KEY (work_id)    REFERENCES works (id),
    CONSTRAINT fk_work_authors_author  FOREIGN KEY (author_id)  REFERENCES authors (id),
    CONSTRAINT fk_work_authors_role    FOREIGN KEY (author_role_id) REFERENCES author_roles (id)
);

CREATE TABLE edition_authors (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    edition_id   BIGINT       NOT NULL,
    author_id    BIGINT       NOT NULL,
    author_role_id BIGINT,
    role         VARCHAR(100),
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    CONSTRAINT fk_edition_authors_edition FOREIGN KEY (edition_id) REFERENCES editions (id),
    CONSTRAINT fk_edition_authors_author  FOREIGN KEY (author_id)  REFERENCES authors (id),
    CONSTRAINT fk_edition_authors_role    FOREIGN KEY (author_role_id) REFERENCES author_roles (id)
);

-- STOCK
CREATE TABLE stock_locations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(500),
    capacity        INTEGER,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    CONSTRAINT uk_stock_locations_code UNIQUE (code)
);

CREATE TABLE stock_items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    edition_id      BIGINT       NOT NULL,
    location_id     BIGINT       NOT NULL,
    reservation_id  BIGINT,
    state           VARCHAR(20)  NOT NULL DEFAULT 'AVAILABLE',
    condition       VARCHAR(20)  NOT NULL DEFAULT 'GOOD',
    daily_price     DECIMAL(10,2) DEFAULT 10.00,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    CONSTRAINT uk_stock_items_code UNIQUE (code),
    CONSTRAINT fk_stock_items_edition  FOREIGN KEY (edition_id)   REFERENCES editions (id),
    CONSTRAINT fk_stock_items_location FOREIGN KEY (location_id)  REFERENCES stock_locations (id)
);

CREATE TABLE stock_movements (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type                VARCHAR(20)  NOT NULL,
    stock_item_id       BIGINT       NOT NULL,
    source_location_id  BIGINT,
    target_location_id  BIGINT,
    reason              VARCHAR(500),
    created_at          TIMESTAMP(6) WITH TIME ZONE,
    created_by          VARCHAR(50),
    CONSTRAINT fk_stock_movements_item      FOREIGN KEY (stock_item_id)        REFERENCES stock_items (id),
    CONSTRAINT fk_stock_movements_source    FOREIGN KEY (source_location_id)   REFERENCES stock_locations (id),
    CONSTRAINT fk_stock_movements_target    FOREIGN KEY (target_location_id)   REFERENCES stock_locations (id)
);

-- CLIENT
CREATE TABLE clients (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL,
    dni             VARCHAR(20)  NOT NULL,
    full_name       VARCHAR(150),
    email           VARCHAR(150),
    phone           VARCHAR(20),
    address         VARCHAR(300),
    type            VARCHAR(20)  NOT NULL DEFAULT 'CASUAL',
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    member_since    DATE,
    member_until    DATE,
    birth_date      DATE,
    notes           VARCHAR(500),
    membership_paid BOOLEAN      NOT NULL DEFAULT FALSE,
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    CONSTRAINT uk_clients_code UNIQUE (code),
    CONSTRAINT uk_clients_dni UNIQUE (dni)
);

-- RESERVATION
CREATE TABLE reservations (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(50)  NOT NULL,
    client_id               BIGINT       NOT NULL,
    edition_id              BIGINT       NOT NULL,
    stock_item_id           BIGINT,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'DEPOSIT_PENDING',
    deposit_percentage      INTEGER      NOT NULL DEFAULT 50,
    deposit_amount          DECIMAL(10,2),
    deposit_paid            BOOLEAN      NOT NULL DEFAULT FALSE,
    total_amount            DECIMAL(10,2),
    total_paid              DECIMAL(10,2) DEFAULT 0,
    reservation_date        TIMESTAMP(6) WITH TIME ZONE,
    pickup_deadline         DATE,
    pickup_date             TIMESTAMP(6) WITH TIME ZONE,
    due_date                DATE,
    return_date             TIMESTAMP(6) WITH TIME ZONE,
    late_fee_per_day        DECIMAL(10,2) DEFAULT 1.00,
    late_fee_total          DECIMAL(10,2) DEFAULT 0,
    renewal_count           INTEGER      DEFAULT 0,
    max_renewals            INTEGER      DEFAULT 1,
    notes                   VARCHAR(500),
    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP(6) WITH TIME ZONE,
    updated_at              TIMESTAMP(6) WITH TIME ZONE,
    created_by              VARCHAR(50),
    updated_by              VARCHAR(50),
    deleted_at              TIMESTAMP(6) WITH TIME ZONE,
    deleted_by              VARCHAR(50),
    CONSTRAINT uk_reservations_code UNIQUE (code),
    CONSTRAINT fk_reservations_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_reservations_edition FOREIGN KEY (edition_id) REFERENCES editions (id),
    CONSTRAINT fk_reservations_stock_item FOREIGN KEY (stock_item_id) REFERENCES stock_items (id)
);

CREATE TABLE payment_methods (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(30)  NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6),
    updated_at   TIMESTAMP(6),
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50)
);

CREATE TABLE accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(200) NOT NULL,
    type         VARCHAR(20)  NOT NULL,
    description  VARCHAR(500),
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);

CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL UNIQUE,
    payment_date    DATE         NOT NULL,
    amount          DECIMAL(12,2) NOT NULL,
    payment_method  VARCHAR(30)  NOT NULL,
    category        VARCHAR(30)  NOT NULL,
    client_id       BIGINT,
    client_name     VARCHAR(200),
    reference_type  VARCHAR(50),
    reference_id    BIGINT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'COMPLETED',
    received_by     VARCHAR(100),
    notes           VARCHAR(500),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50)
);

CREATE TABLE refunds (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    refund_date  DATE         NOT NULL,
    amount       DECIMAL(12,2) NOT NULL,
    reason       VARCHAR(500),
    payment_id   BIGINT,
    client_id    BIGINT,
    client_name  VARCHAR(200),
    processed_by VARCHAR(100),
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    notes        VARCHAR(500),
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);

CREATE TABLE payroll_payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(50)  NOT NULL UNIQUE,
    payment_date   DATE         NOT NULL,
    employee_id    BIGINT       NOT NULL,
    employee_name  VARCHAR(200),
    amount         DECIMAL(12,2) NOT NULL,
    period_month   INTEGER,
    period_year    INTEGER,
    payment_method VARCHAR(30),
    status         VARCHAR(20)  NOT NULL DEFAULT 'PAID',
    notes          VARCHAR(500),
    processed_by   VARCHAR(100),
    created_at     TIMESTAMP(6) WITH TIME ZONE,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    created_by     VARCHAR(50),
    updated_by     VARCHAR(50),
    deleted_at     TIMESTAMP(6) WITH TIME ZONE,
    deleted_by     VARCHAR(50)
);

CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL UNIQUE,
    expense_date    DATE         NOT NULL,
    category        VARCHAR(30)  NOT NULL,
    description     VARCHAR(500) NOT NULL,
    amount          DECIMAL(12,2) NOT NULL,
    payment_method  VARCHAR(30),
    vendor          VARCHAR(200),
    receipt_number  VARCHAR(100),
    notes           VARCHAR(500),
    created_by      VARCHAR(100),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50)
);
-- CONFIG

CREATE TABLE settings (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module     VARCHAR(50)  NOT NULL,
    setting_key VARCHAR(100) NOT NULL,
    setting_value TEXT       NOT NULL,
    setting_type VARCHAR(20)  NOT NULL,
    description TEXT,
    updated_at TIMESTAMP    NOT NULL,
    updated_by VARCHAR(50)
);

CREATE UNIQUE INDEX uk_settings_module_key ON settings (module, setting_key);

-- AUDIT TABLES
CREATE TABLE REVINFO (
    REV      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    REVTSTMP BIGINT,
    username VARCHAR(50)
);

CREATE TABLE modules_AUD (
    id          BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), name VARCHAR(100), menu_label VARCHAR(150), icon VARCHAR(100),
    sort_order INTEGER, enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE, created_by VARCHAR(50), updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE, deleted_by VARCHAR(50),
    PRIMARY KEY (id, REV), CONSTRAINT fk_modules_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE permissions_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(100), name VARCHAR(150), menu_label VARCHAR(255), icon VARCHAR(100),
    url VARCHAR(255), sort_order INTEGER, enabled BOOLEAN, module_id BIGINT,
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_permissions_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE roles_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    name VARCHAR(50), description VARCHAR(255), enabled BOOLEAN,
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_roles_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE role_permissions_AUD (
    role_id BIGINT NOT NULL, permission_id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    PRIMARY KEY (role_id, permission_id, REV),
    CONSTRAINT fk_rp_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE users_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    username VARCHAR(50), password VARCHAR(255), full_name VARCHAR(150), email VARCHAR(120),
    enabled BOOLEAN, failed_login_attempts INTEGER, locked_until TIMESTAMP(6) WITH TIME ZONE,
    role_id BIGINT, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_users_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE works_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    title VARCHAR(300), subtitle VARCHAR(500), original_language_id BIGINT, category_id BIGINT,
    summary VARCHAR(2000), enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE, created_by VARCHAR(50), updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE, deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_works_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE editions_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    work_id BIGINT, publisher_id BIGINT, format_id BIGINT, language_id BIGINT,
    isbn VARCHAR(20), pages INTEGER, publication_year INTEGER, edition_number VARCHAR(50), daily_price DECIMAL(10,2),
    enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_editions_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE authors_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    first_name VARCHAR(100), last_name VARCHAR(100), biography VARCHAR(2000),
    birth_date VARCHAR(20), death_date VARCHAR(20), enabled BOOLEAN,
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_authors_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE publishers_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    name VARCHAR(200), country VARCHAR(100), website VARCHAR(300), enabled BOOLEAN,
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_publishers_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE languages_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(20), name VARCHAR(100), enabled BOOLEAN,
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_languages_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE book_formats_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), name VARCHAR(100), description VARCHAR(500), enabled BOOLEAN,
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_book_formats_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE categories_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), name VARCHAR(150), description VARCHAR(1000), parent_id BIGINT,
    enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_categories_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE work_authors_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    work_id BIGINT, author_id BIGINT, author_role_id BIGINT, role VARCHAR(100),
    enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_work_authors_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE edition_authors_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    edition_id BIGINT, author_id BIGINT, author_role_id BIGINT, role VARCHAR(100),
    enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_edition_authors_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE author_roles_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), name VARCHAR(100), description VARCHAR(255),
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_author_roles_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE stock_locations_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), name VARCHAR(100), description VARCHAR(500), capacity INTEGER,
    enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_stock_locations_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE stock_items_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), edition_id BIGINT, location_id BIGINT, reservation_id BIGINT,
    state VARCHAR(20), condition VARCHAR(20), daily_price DECIMAL(10,2), enabled BOOLEAN,
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_stock_items_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE stock_movements_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    type VARCHAR(20), stock_item_id BIGINT, source_location_id BIGINT, target_location_id BIGINT,
    reason VARCHAR(500), created_at TIMESTAMP(6) WITH TIME ZONE, created_by VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_stock_movements_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE clients_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), dni VARCHAR(20), full_name VARCHAR(150), email VARCHAR(150),
    phone VARCHAR(20), address VARCHAR(300), type VARCHAR(20), status VARCHAR(20),
    member_since DATE, member_until DATE, birth_date DATE, notes VARCHAR(500),
    membership_paid BOOLEAN, enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE, created_by VARCHAR(50), updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE, deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_clients_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE reservations_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), client_id BIGINT, edition_id BIGINT, stock_item_id BIGINT,
    status VARCHAR(20), deposit_percentage INTEGER, deposit_amount DECIMAL(10,2),
    deposit_paid BOOLEAN, total_amount DECIMAL(10,2), total_paid DECIMAL(10,2),
    reservation_date TIMESTAMP(6) WITH TIME ZONE, pickup_deadline DATE, pickup_date TIMESTAMP(6) WITH TIME ZONE,
    due_date DATE, return_date TIMESTAMP(6) WITH TIME ZONE, late_fee_per_day DECIMAL(10,2),
    late_fee_total DECIMAL(10,2), renewal_count INTEGER, max_renewals INTEGER, notes VARCHAR(500),
    enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_reservations_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE accounts_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), name VARCHAR(200), type VARCHAR(20), description VARCHAR(500),
    enabled BOOLEAN, created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    created_by VARCHAR(50), updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE,
    deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_accounts_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE payment_methods_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(30), name VARCHAR(100), enabled BOOLEAN,
    created_at TIMESTAMP(6), updated_at TIMESTAMP(6),
    created_by VARCHAR(50), updated_by VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_payment_methods_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE payments_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), payment_date DATE, amount DECIMAL(12,2), payment_method VARCHAR(30),
    category VARCHAR(30), client_id BIGINT, client_name VARCHAR(200),
    reference_type VARCHAR(50), reference_id BIGINT, status VARCHAR(20),
    received_by VARCHAR(100), notes VARCHAR(500), created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE, created_by VARCHAR(50), updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE, deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_payments_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE refunds_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), refund_date DATE, amount DECIMAL(12,2), reason VARCHAR(500),
    payment_id BIGINT, client_id BIGINT, client_name VARCHAR(200), processed_by VARCHAR(100),
    status VARCHAR(20), notes VARCHAR(500), created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE, created_by VARCHAR(50), updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE, deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_refunds_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE payroll_payments_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), payment_date DATE, employee_id BIGINT, employee_name VARCHAR(200),
    amount DECIMAL(12,2), period_month INTEGER, period_year INTEGER,
    payment_method VARCHAR(30), status VARCHAR(20), notes VARCHAR(500),
    processed_by VARCHAR(100), created_at TIMESTAMP(6) WITH TIME ZONE,
    updated_at TIMESTAMP(6) WITH TIME ZONE, created_by VARCHAR(50), updated_by VARCHAR(50),
    deleted_at TIMESTAMP(6) WITH TIME ZONE, deleted_by VARCHAR(50), PRIMARY KEY (id, REV),
    CONSTRAINT fk_payroll_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE expenses_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    code VARCHAR(50), expense_date DATE, category VARCHAR(30), description VARCHAR(500),
    amount DECIMAL(12,2), payment_method VARCHAR(30), vendor VARCHAR(200),
    receipt_number VARCHAR(100), notes VARCHAR(500), created_by VARCHAR(100),
    created_at TIMESTAMP(6) WITH TIME ZONE, updated_at TIMESTAMP(6) WITH TIME ZONE,
    updated_by VARCHAR(50), deleted_at TIMESTAMP(6) WITH TIME ZONE, deleted_by VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_expenses_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

CREATE TABLE settings_AUD (
    id BIGINT NOT NULL, REV BIGINT NOT NULL, REVTYPE SMALLINT,
    module VARCHAR(50), setting_key VARCHAR(100), setting_value TEXT, setting_type VARCHAR(20),
    description TEXT, updated_at TIMESTAMP, updated_by VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_settings_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
