-- ============================================================================
-- V17__reservation.sql
-- Reservation module: reservations table and stock_items.reservation_id column.
-- ============================================================================

-- Agregar reservation_id a stock_items para trackear reserva activa
ALTER TABLE stock_items ADD COLUMN reservation_id BIGINT;

-- Tabla de reservaciones
CREATE TABLE reservations (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                    VARCHAR(50)  NOT NULL,
    client_id               BIGINT       NOT NULL,
    edition_id              BIGINT       NOT NULL,
    stock_item_id           BIGINT,
    status                  VARCHAR(20)  NOT NULL DEFAULT 'DEPOSIT_PENDING',
    deposit_percentage      INTEGER      NOT NULL DEFAULT 50,
    deposit_amount          DECIMAL(10,2),
    deposit_paid            BOOLEAN      NOT NULL DEFAULT FALSE,
    total_amount            DECIMAL(10,2),
    total_paid              DECIMAL(10,2) DEFAULT 0,
    reservation_date        TIMESTAMP(6) WITH TIME ZONE,
    pickup_deadline         DATE,
    pickup_date             TIMESTAMP(6) WITH TIME ZONE,
    due_date                DATE,
    return_date             TIMESTAMP(6) WITH TIME ZONE,
    late_fee_per_day        DECIMAL(10,2) DEFAULT 10.00,
    late_fee_total          DECIMAL(10,2) DEFAULT 0,
    renewal_count           INTEGER      DEFAULT 0,
    max_renewals            INTEGER      DEFAULT 1,
    notes                   VARCHAR(500),
    enabled                 BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at              TIMESTAMP(6) WITH TIME ZONE,
    updated_at              TIMESTAMP(6) WITH TIME ZONE,
    created_by              VARCHAR(50),
    updated_by              VARCHAR(50),
    deleted_at              TIMESTAMP(6) WITH TIME ZONE,
    deleted_by              VARCHAR(50),
    CONSTRAINT uk_reservations_code UNIQUE (code),
    CONSTRAINT fk_reservations_client FOREIGN KEY (client_id) REFERENCES clients (id),
    CONSTRAINT fk_reservations_edition FOREIGN KEY (edition_id) REFERENCES editions (id),
    CONSTRAINT fk_reservations_stock_item FOREIGN KEY (stock_item_id) REFERENCES stock_items (id)
);

-- ============================================================================
-- Módulo Reservation: permisos y grants
-- ============================================================================

INSERT INTO modules (code, name, menu_label, icon, sort_order, enabled) VALUES
    ('reservation', 'Reservations', 'Reservations', 'bi-calendar-check', 6, TRUE);

INSERT INTO permissions (code, name, menu_label, icon, url, sort_order, module_id) VALUES
    ('reservations.create',       'Create Reservations',     NULL,            NULL, NULL, 10, 6),
    ('reservations.read',         'View Reservations',       'Reservations', 'bi-calendar-check', '/reservations', 11, 6),
    ('reservations.update',       'Edit Reservations',       NULL,            NULL, NULL, 12, 6),
    ('reservations.delete',       'Delete Reservations',     NULL,            NULL, NULL, 13, 6),
    ('reservations.cancel',       'Cancel Reservations',     NULL,            NULL, NULL, 14, 6),
    ('reservations.fulfill',      'Fulfill Reservations',    NULL,            NULL, NULL, 15, 6),
    ('reservations.return',       'Process Returns',         NULL,            NULL, NULL, 16, 6),
    ('reservations.renew',        'Renew Reservations',      NULL,            NULL, NULL, 17, 6),
    ('reservations.config',       'Configure Reservations',  NULL,            NULL, NULL, 18, 6);

-- Grant all reservation permissions to ADMIN
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'ADMIN'
  AND p.module_id = 6;

-- Grant read permission to EMPLOYEE
INSERT INTO role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM roles r CROSS JOIN permissions p
WHERE r.name = 'EMPLOYEE'
  AND p.code = 'reservations.read';

-- ============================================================================
-- Envers audit tables (_AUD) for @Audited reservation entities.
-- ============================================================================

CREATE TABLE reservations_AUD (
    id                      BIGINT NOT NULL,
    REV                     BIGINT NOT NULL,
    REVTYPE                 SMALLINT,
    code                    VARCHAR(50),
    client_id               BIGINT,
    edition_id              BIGINT,
    stock_item_id           BIGINT,
    status                  VARCHAR(20),
    deposit_percentage      INTEGER,
    deposit_amount          DECIMAL(10,2),
    deposit_paid            BOOLEAN,
    total_amount            DECIMAL(10,2),
    total_paid              DECIMAL(10,2),
    reservation_date        TIMESTAMP(6) WITH TIME ZONE,
    pickup_deadline         DATE,
    pickup_date             TIMESTAMP(6) WITH TIME ZONE,
    due_date                DATE,
    return_date             TIMESTAMP(6) WITH TIME ZONE,
    late_fee_per_day        DECIMAL(10,2),
    late_fee_total          DECIMAL(10,2),
    renewal_count           INTEGER,
    max_renewals            INTEGER,
    notes                   VARCHAR(500),
    enabled                 BOOLEAN,
    created_at              TIMESTAMP(6) WITH TIME ZONE,
    updated_at              TIMESTAMP(6) WITH TIME ZONE,
    created_by              VARCHAR(50),
    updated_by              VARCHAR(50),
    deleted_at              TIMESTAMP(6) WITH TIME ZONE,
    deleted_by              VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_reservations_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
