-- ============================================================================
-- V21__accounting_schema.sql
-- Accounting module: chart of accounts, payments, payroll, expenses, refunds.
-- ============================================================================

-- Chart of accounts -------------------------------------------------------
CREATE TABLE accounts (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    name         VARCHAR(200) NOT NULL,
    type         VARCHAR(20)  NOT NULL,
    description  VARCHAR(500),
    enabled      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);
CREATE TABLE accounts_AUD (
    id           BIGINT NOT NULL,
    REV          BIGINT NOT NULL,
    REVTYPE      SMALLINT,
    code         VARCHAR(50),
    name         VARCHAR(200),
    type         VARCHAR(20),
    description  VARCHAR(500),
    enabled      BOOLEAN,
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_accounts_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Payments (from clients) -------------------------------------------------
CREATE TABLE payments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL UNIQUE,
    payment_date    DATE         NOT NULL,
    amount          DECIMAL(12,2) NOT NULL,
    payment_method  VARCHAR(30)  NOT NULL,
    category        VARCHAR(30)  NOT NULL,
    client_id       BIGINT,
    client_name     VARCHAR(200),
    reference_type  VARCHAR(50),
    reference_id    BIGINT,
    status          VARCHAR(20)  NOT NULL DEFAULT 'COMPLETED',
    received_by     VARCHAR(100),
    notes           VARCHAR(500),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50)
);
CREATE TABLE payments_AUD (
    id              BIGINT NOT NULL,
    REV             BIGINT NOT NULL,
    REVTYPE         SMALLINT,
    code            VARCHAR(50),
    payment_date    DATE,
    amount          DECIMAL(12,2),
    payment_method  VARCHAR(30),
    category        VARCHAR(30),
    client_id       BIGINT,
    client_name     VARCHAR(200),
    reference_type  VARCHAR(50),
    reference_id    BIGINT,
    status          VARCHAR(20),
    received_by     VARCHAR(100),
    notes           VARCHAR(500),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    created_by      VARCHAR(50),
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_payments_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Refunds -----------------------------------------------------------------
CREATE TABLE refunds (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code         VARCHAR(50)  NOT NULL UNIQUE,
    refund_date  DATE         NOT NULL,
    amount       DECIMAL(12,2) NOT NULL,
    reason       VARCHAR(500),
    payment_id   BIGINT,
    client_id    BIGINT,
    client_name  VARCHAR(200),
    processed_by VARCHAR(100),
    status       VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    notes        VARCHAR(500),
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50)
);
CREATE TABLE refunds_AUD (
    id           BIGINT NOT NULL,
    REV          BIGINT NOT NULL,
    REVTYPE      SMALLINT,
    code         VARCHAR(50),
    refund_date  DATE,
    amount       DECIMAL(12,2),
    reason       VARCHAR(500),
    payment_id   BIGINT,
    client_id    BIGINT,
    client_name  VARCHAR(200),
    processed_by VARCHAR(100),
    status       VARCHAR(20),
    notes        VARCHAR(500),
    created_at   TIMESTAMP(6) WITH TIME ZONE,
    updated_at   TIMESTAMP(6) WITH TIME ZONE,
    created_by   VARCHAR(50),
    updated_by   VARCHAR(50),
    deleted_at   TIMESTAMP(6) WITH TIME ZONE,
    deleted_by   VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_refunds_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Payroll payments --------------------------------------------------------
CREATE TABLE payroll_payments (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code           VARCHAR(50)  NOT NULL UNIQUE,
    payment_date   DATE         NOT NULL,
    employee_id    BIGINT       NOT NULL,
    employee_name  VARCHAR(200),
    amount         DECIMAL(12,2) NOT NULL,
    period_month   INTEGER,
    period_year    INTEGER,
    payment_method VARCHAR(30),
    status         VARCHAR(20)  NOT NULL DEFAULT 'PAID',
    notes          VARCHAR(500),
    processed_by   VARCHAR(100),
    created_at     TIMESTAMP(6) WITH TIME ZONE,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    created_by     VARCHAR(50),
    updated_by     VARCHAR(50),
    deleted_at     TIMESTAMP(6) WITH TIME ZONE,
    deleted_by     VARCHAR(50)
);
CREATE TABLE payroll_payments_AUD (
    id             BIGINT NOT NULL,
    REV            BIGINT NOT NULL,
    REVTYPE        SMALLINT,
    code           VARCHAR(50),
    payment_date   DATE,
    employee_id    BIGINT,
    employee_name  VARCHAR(200),
    amount         DECIMAL(12,2),
    period_month   INTEGER,
    period_year    INTEGER,
    payment_method VARCHAR(30),
    status         VARCHAR(20),
    notes          VARCHAR(500),
    processed_by   VARCHAR(100),
    created_at     TIMESTAMP(6) WITH TIME ZONE,
    updated_at     TIMESTAMP(6) WITH TIME ZONE,
    created_by     VARCHAR(50),
    updated_by     VARCHAR(50),
    deleted_at     TIMESTAMP(6) WITH TIME ZONE,
    deleted_by     VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_payroll_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);

-- Expenses (local operating costs) ---------------------------------------
CREATE TABLE expenses (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code            VARCHAR(50)  NOT NULL UNIQUE,
    expense_date    DATE         NOT NULL,
    category        VARCHAR(30)  NOT NULL,
    description     VARCHAR(500) NOT NULL,
    amount          DECIMAL(12,2) NOT NULL,
    payment_method  VARCHAR(30),
    vendor          VARCHAR(200),
    receipt_number  VARCHAR(100),
    notes           VARCHAR(500),
    created_by      VARCHAR(100),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50)
);
CREATE TABLE expenses_AUD (
    id              BIGINT NOT NULL,
    REV             BIGINT NOT NULL,
    REVTYPE         SMALLINT,
    code            VARCHAR(50),
    expense_date    DATE,
    category        VARCHAR(30),
    description     VARCHAR(500),
    amount          DECIMAL(12,2),
    payment_method  VARCHAR(30),
    vendor          VARCHAR(200),
    receipt_number  VARCHAR(100),
    notes           VARCHAR(500),
    created_by      VARCHAR(100),
    created_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_at      TIMESTAMP(6) WITH TIME ZONE,
    updated_by      VARCHAR(50),
    deleted_at      TIMESTAMP(6) WITH TIME ZONE,
    deleted_by      VARCHAR(50),
    PRIMARY KEY (id, REV),
    CONSTRAINT fk_expenses_aud_rev FOREIGN KEY (REV) REFERENCES REVINFO (REV)
);
